---
driver:
  name: docker

driver_config:
  privileged: true
  use_sudo: false
  cap_add:
    - ALL

provisioner:
  require_ansible_repo: false
  idempotency_test: true
  require_chef_for_busser: false
  require_ruby_for_busser: true
  ansible_verbose: false
  ansible_verbosity: 2

  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  hosts: localhost

platforms:

  - name: ubuntu-trusty
    driver_config:
      image: hub.alterway.fr/kitchen-ansible:trusty-2.2

  - name: debian-wheezy
    driver_config:
      image: hub.alterway.fr/kitchen-ansible:wheezy-2.2

  - name: debian-jessie
    driver_config:
      image: hub.alterway.fr/kitchen-ansible:jessie-2.2

  - name: ubuntu-xenial
    driver_config:
      image: hub.alterway.fr/kitchen-ansible:xenial-2.2

  - name: centos-7
    driver_config:
      image: hub.alterway.fr/kitchen-ansible:centos7-2.2
      run_command: /usr/sbin/init
    verifier:
      ruby_bindir: '/usr/local/bin'

  - name: centos-6
    driver_config:
      image: hub.alterway.fr/kitchen-ansible:centos6-2.2
    verifier:
      ruby_bindir: '/usr/local/bin'

verifier:
  ruby_bindir: '/usr/bin'

suites:

  - name: empty
    provisioner:
      name: ansible_playbook
      playbook: test/integration/empty.yml

  - name: cron
    provisioner:
      playbook: test/integration/cron.yml