---
- name: Template /etc/automysqlbackup/myserver.conf
  template:
    src: 'myserver.conf.j2'
    dest: '/etc/automysqlbackup/{{ item }}.conf'
    mode: '750'
    owner: 'root'
  with_items:
    - "{{ automysqlbackup_conf_name }}"
