---
- name: Include install.yml
  include: install.yml
  tags:
    - automysqlbackup
    - automysqlbackup_install

- name: Include configure.yml
  include: configure.yml
  tags:
    - automysqlbackup
    - automysqlbackup_configure

- name: Include cron.yml
  include: cron.yml
  when: automysqlbackup_cron is defined
  tags:
    - automysqlbackup
    - automysqlbackup_configure
    - automysqlbackup_cron
